server:
  port: 9500
spring:
  application:
    name: spring-cloud-zuul


eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka/

info:
  app.name: whitestorm
  company.name: blog.whitestorm

zuul:
  routes:
#    修改应用名称映射
    mydet.serviceId: spring-cloud-producer-dept
    mydet.path: /mydept/**
    #不能再使用这个路径访问了
#  ignored-services: spring-cloud-producer-dept
#  隐藏全部
  ignored-services: "*"
  prefix: /whitestorm #设置公共前缀