server:
  port: 80

spring:
  application:
    name: spring-cloud-consumer-80
#Eureka配置
eureka:
  client:
#    register-with-eureka: false # 不想eureka注册自己
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka/

